chord:
  num_successors: 3 # successors list length for each node
  max_ring_size: 1000 # maximum number of nodes in the ring
  retry_limit: 4 # number of times to retry a request for a node
  retry_interval: 4000 # time to wait before retrying a request for a node 


tcp_server:
  allow_none: True
  log_requests: True
